version: 2
registries:
  python-index-pypi-python-org-simple:
    type: python-index
    url: https://pypi.python.org/simple/

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  registries:
  - python-index-pypi-python-org-simple
